In [1]:
import pandas as pd
import scipy.stats as stats
import numpy as np
import matplotlib as plt
import math

# Case Study 1:
    

A physician is evaluating a new diet for her patients with a family history of heart disease. To test the effectiveness of this diet, 16 patients are placed on the diet for 6 months. Their weights and triglyceride levels are measured before and after the study, and the physician wants to know if either set of measurements has changed. (Data set: dietstudy.csv) 

In [6]:
diet_study = pd.read_csv("E:\\DataScienceWithPython\\Python Assignments Code\\7.BasicStatsCaseStudy-1\\dietstudy.csv")

In [7]:
diet_study.head(5)

patid  age  gender  tg0  tg1  tg2  tg3  tg4  wgt0  wgt1  wgt2  wgt3  wgt4
0      1   45    Male  180  148  106  113  100   198   196   193   188   192
1      2   56    Male  139   94  119   75   92   237   233   232   228   225
2      3   50    Male  152  185   86  149  118   233   231   229   228   226
3      4   46  Female  112  145  136  149   82   179   181   177   174   172
4      5   64    Male  156  104  157   79   97   219   217   215   213   214

In [8]:
stats.ttest_rel(diet_study.tg0,diet_study.tg4)

Ttest_relResult(statistic=1.2000008533342437, pvalue=0.24874946576903698)

In [9]:
stats.ttest_rel(diet_study.wgt0,diet_study.wgt4)

Ttest_relResult(statistic=11.174521688532522, pvalue=1.137689414996614e-08)

Conclusion:
    For Triglyceride, Since P value > Significance value(5%). Accept the Null. 
    Therefore no change in Triglyceride.
    For Weight, P value < Significance value(5%) Reject the Null and statistics value is Negative, it means it is Left tailed test. 
    Set of Weight measures are Decreased. 
    

# Case Study 2:

An analyst at a department store wants to evaluate a recent credit card promotion. To this end, 500 cardholders were randomly selected. Half received an ad promoting a reduced interest rate on purchases made over the next three months, and half received a standard seasonal ad. Is the promotion effective to increase sales? (Data set: creditpromo.csv) 

In [11]:
credit_promo = pd.read_csv("E:\\DataScienceWithPython\\Python Assignments Code\\7.BasicStatsCaseStudy-1\\creditpromo.csv")

In [12]:
credit_promo.head(5)

id         insert      dollars
0   148       Standard  2232.771979
1   572  New Promotion  1403.807542
2   973       Standard  2327.092181
3  1096       Standard  1280.030541
4  1541  New Promotion  1513.563200

In [21]:
std_promo = credit_promo.dollars[credit_promo['insert'] =='Standard']
new_promo = credit_promo.dollars[credit_promo['insert'] =='New Promotion']

In [22]:
stats.ttest_ind(std_promo, new_promo, equal_var = False)

Ttest_indResult(statistic=-2.260422726464996, pvalue=0.024226348191648994)

Conslusion:
    Since p-value < significant value(5%) so reject the null and stats value is -ve means left tailed test.
    So New Promotion was effective as sales is increased for New promotion customers.

# Case Study 3:

An experiment is conducted to study the hybrid seed production of bottle gourd under open field conditions. The main aim of the investigation is to compare natural pollination and hand pollination. The data are collected on 10 randomly selected plants from each of natural pollination and hand pollination. 
The data are collected on fruit weight (kg), seed yield/plant (g) and seedling length (cm). (Data set: pollination.csv) 
    a. Is the overall population of Seed yield/plant (g) equals to 200? 
    b. Test whether the natural pollination and hand pollination under open field conditions are equally effective or are significantly different.

In [29]:
pollination = pd.read_csv("E:\\DataScienceWithPython\\Python Assignments Code\\7.BasicStatsCaseStudy-1\\pollination.csv")

In [24]:
pollination.head(5)

Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0  Natural      1.85            147.70            16.86
1  Natural      1.86            136.86            16.77
2  Natural      1.83            149.97            16.35
3  Natural      1.89            172.33            18.26
4  Natural      1.80            144.46            17.90

In [25]:
stats.ttest_1samp(a=pollination.Seed_Yield_Plant, popmean=200)

Ttest_1sampResult(statistic=-2.3009121248548645, pvalue=0.032891040921283025)

In [ ]:
Conclusion (a): Single sample t-test
    Since p-value < significant value(5%) so Reject the Null and stats value is -ve means left tailed test.
    So Overall population of Seed_Yield_Plant is less than 200.

In [28]:
fruit_wt_N = pollination.Fruit_Wt[pollination['Group']=='Natural']
fruit_wt_H = pollination.Fruit_Wt[pollination['Group']=='Hand']

In [30]:
seed_plant_N = pollination.Seed_Yield_Plant[pollination['Group']== 'Natural']
seed_plant_H = pollination.Seed_Yield_Plant[pollination['Group']== 'Hand']

In [31]:
seeding_len_N = pollination.Seedling_length[pollination['Group']== 'Natural']
seeding_len_H = pollination.Seedling_length[pollination['Group']== 'Hand']

In [33]:
stats.ttest_ind(a=fruit_wt_N,b=fruit_wt_H, equal_var=False)

Ttest_indResult(statistic=-17.669989614440286, pvalue=4.306871213074868e-09)

Result:
    Since P-value < significance value(5%), Reject the Null and Stats value is -ve means its Left tail test.
    So Fruit  Weight of Natural pollination is less than Hand pollination.

In [34]:
stats.ttest_ind(a=seed_plant_N,b=seed_plant_H, equal_var= False)

Ttest_indResult(statistic=-13.958260515902547, pvalue=5.136161282685624e-11)

Result:
    Since P-value < significance value(5%), Reject the Null and Stats value is -ve means its Left tail test.
    So Seed plant of Natural pollination is smaller than Hand pollination.

In [35]:
stats.ttest_ind(a=seeding_len_N, b=seeding_len_H, equal_var = False)

Ttest_indResult(statistic=-2.542229999657055, pvalue=0.021430608378161634)

Result:
    Since P-value < significance value(5%), Reject the Null and Stats value is -ve means its Left tail test.
    So Seed length of Natural pollination is lesser than Hand pollination.

Conclusion (b): 2 sample t-test (unpaired)
    Since p-value < significant value(5%) so reject the null and stats value is -ve means left tailed test for all 3 tests.
    So Natual pollination is less effective than Hand pollination.

# Case Study 4:

An electronics firm is developing a new DVD player in response to customer requests. Using a prototype, the marketing team has collected focus data for different age groups viz. Under 25; 25-34; 35-44; 45-54; 55-64; 65 and over. Do you think that consumers of various ages rated the design differently? (Data set: dvdplayer.csv).

In [52]:
dvd = pd.read_csv("E:\\DataScienceWithPython\\Python Assignments Code\\7.BasicStatsCaseStudy-1\\dvdplayer.csv")

In [55]:
age_Group1 = dvd.dvdscore[dvd['agegroup']=='Under 25']
age_Group2 = dvd.dvdscore[dvd['agegroup']=='25-34']
age_Group3 = dvd.dvdscore[dvd['agegroup']=='35-44']
age_Group4 = dvd.dvdscore[dvd['agegroup']=='45-54']
age_Group5 = dvd.dvdscore[dvd['agegroup']=='55-64']
age_Group6 = dvd.dvdscore[dvd['agegroup']=='65 and over']

In [57]:
stats.f_oneway(age_Group1,age_Group2,age_Group3,age_Group4,age_Group5,age_Group6)

F_onewayResult(statistic=6.992526962676518, pvalue=3.087324905679639e-05)

Conclusion: ANOVA test as more than 2 means to be validated. 
    H0: All means are equal
    H1: Atleast one mean is different.
    Since P-value < significance value(5%), Reject the Null.
    Atleast one Age Group rated the design differently.

# Case Study 5:

A survey was conducted among 2800 customers on several demographic characteristics. Working status, sex, age, age-group, race, happiness, no. of child, marital status, educational qualifications, income group etc. had been captured for that purpose. (Data set: sample_survey.csv).  
a. Is there any relationship in between labour force status with marital status? b. Do you think educational qualification is somehow controlling the marital status?  c. Is happiness is driven by earnings or marital status?

In [58]:
survey = pd.read_csv("E:\\DataScienceWithPython\\Python Assignments Code\\7.BasicStatsCaseStudy-1\\sample_survey.csv")

In [59]:
survey.head(5)

id            wrkstat        marital  childs   age  educ  paeduc  maeduc  \
0   1  Working full time       Divorced     2.0  60.0  12.0    12.0    12.0   
1   2  Working part-time  Never married     0.0  27.0  17.0    20.0     NaN   
2   3  Working full time        Married     2.0  36.0  12.0    12.0    12.0   
3   4  Working full time  Never married     0.0  21.0  13.0     NaN    12.0   
4   5  Working full time  Never married     0.0  35.0  16.0     NaN    12.0   

   speduc          degree    ...           agecat childcat news1 news2  news3  \
0     NaN     High school    ...         55 to 64      1-2    No    No     No   
1     NaN  Junior college    ...         25 to 34     None    No    No    Yes   
2    16.0     High school    ...         35 to 44      1-2    No    No     No   
3     NaN     High school    ...     Less than 25     None    No    No     No   
4     NaN        Bachelor    ...         35 to 44     None    No    No     No   

  news4 news5      car1      car2      car3  
0    No    No  American  Japanese  Japanese  
1    No    No  American    German  Japanese  
2   Yes   Yes  American  American       NaN  
3   Yes   Yes  American     Other       NaN  
4    No    No  American  American    Korean  

[5 rows x 46 columns]

In [63]:
rel = pd.crosstab(survey.marital, survey.wrkstat, margins = True)

In [64]:
rel

wrkstat        Keeping house  Other  Retired  School  Temporarily not working  \
marital                                                                         
Divorced                  25     12       53       7                        9   
Married                  200     16      168       9                       23   
Never married             35     14       17      60                       11   
Separated                 13      4        6       2                        1   
Widowed                   55      8      150       1                        2   
All                      328     54      394      79                       46   

wrkstat        Unemployed, laid off  Working full time  Working part-time  \
marital                                                                     
Divorced                         10                295                 35   
Married                          13                778                138   
Never married                    32                392                102   
Separated                         0                 58                  9   
Widowed                           3                 44                 20   
All                              58               1567                304   

wrkstat         All  
marital              
Divorced        446  
Married        1345  
Never married   663  
Separated        93  
Widowed         283  
All            2830

In [62]:
stats.chi2_contingency(observed=rel)

(729.2421426572284,
 1.820339965538765e-127,
 40,
 array([[5.16918728e+01, 8.51024735e+00, 6.20932862e+01, 1.24501767e+01,
         7.24946996e+00, 9.14063604e+00, 2.46954770e+02, 4.79095406e+01,
         4.46000000e+02],
        [1.55886926e+02, 2.56643110e+01, 1.87254417e+02, 3.75459364e+01,
         2.18621908e+01, 2.75653710e+01, 7.44740283e+02, 1.44480565e+02,
         1.34500000e+03],
        [7.68424028e+01, 1.26508834e+01, 9.23045936e+01, 1.85077739e+01,
         1.07766784e+01, 1.35879859e+01, 3.67109894e+02, 7.12197880e+01,
         6.63000000e+02],
        [1.07787986e+01, 1.77455830e+00, 1.29477032e+01, 2.59611307e+00,
         1.51166078e+00, 1.90600707e+00, 5.14950530e+01, 9.99010601e+00,
         9.30000000e+01],
        [3.28000000e+01, 5.40000000e+00, 3.94000000e+01, 7.90000000e+00,
         4.60000000e+00, 5.80000000e+00, 1.56700000e+02, 3.04000000e+01,
         2.83000000e+02],
        [3.28000000e+02, 5.40000000e+01, 3.94000000e+02, 7.90000000e+01,
         4.600000

Conclusion: a. Since P-value < Significance value(5%) so reject the Null.
Therefore, relationship exist between Labrour Work force and Maritial Status.

In [65]:
control = pd.crosstab(survey.marital, survey.educ, margins = True)

In [66]:
control

educ           0.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0  ...   12.0  \
marital                                                           ...          
Divorced         0    0    2    2    2    2    6    9   18    26  ...    125   
Married          1    1    3    2    3   12   11   36   28    48  ...    415   
Never married    1    1    2    1    0    2    0    8    9    21  ...    180   
Separated        0    0    1    0    0    1    0    2    4     3  ...     33   
Widowed          0    3    2    4    3    6    4   27   16    15  ...     98   
All              2    5   10    9    8   23   21   82   75   113  ...    851   

educ           13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0   All  
marital                                                              
Divorced         48    62    26    47    13    12     9    10   444  
Married         118   168    56   214    46    66    21    40  1339  
Never married    71    89    48   116    24    24     8    15   660  
Separated        16     9     3    10     2     1     1     1    93  
Widowed          17    21    13    25     1     6     2     3   283  
All             270   349   146   412    86   109    41    69  2819  

[6 rows x 21 columns]

In [67]:
stats.chi2_contingency(observed = control)

(221.1089644164776,
 3.863342448812233e-11,
 100,
 array([[3.15005321e-01, 7.87513303e-01, 1.57502661e+00, 1.41752394e+00,
         1.26002128e+00, 3.62256119e+00, 3.30755587e+00, 1.29152182e+01,
         1.18126995e+01, 1.77978006e+01, 2.17353672e+01, 1.34034764e+02,
         4.25257183e+01, 5.49684285e+01, 2.29953884e+01, 6.48910961e+01,
         1.35452288e+01, 1.71677900e+01, 6.45760908e+00, 1.08676836e+01,
         4.44000000e+02],
        [9.49982263e-01, 2.37495566e+00, 4.74991132e+00, 4.27492018e+00,
         3.79992905e+00, 1.09247960e+01, 9.97481376e+00, 3.89492728e+01,
         3.56243349e+01, 5.36739979e+01, 6.55487762e+01, 4.04217453e+02,
         1.28247606e+02, 1.65771905e+02, 6.93487052e+01, 1.95696346e+02,
         4.08492373e+01, 5.17740333e+01, 1.94746364e+01, 3.27743881e+01,
         1.33900000e+03],
        [4.68251153e-01, 1.17062788e+00, 2.34125576e+00, 2.10713019e+00,
         1.87300461e+00, 5.38488826e+00, 4.91663711e+00, 1.91982973e+01,
         1.75594182e+0

Conclusion: b. Since P-value < Significance value(5%) so reject the Null.
Therefore, Educational qualification is controlling Maritial Status.

In [74]:
earnings = pd.crosstab(survey.income,survey.happy, margins = True)

In [75]:
stats.chi2_contingency(observed = earnings)

(178.9505306121643,
 7.234749067043263e-21,
 36,
 array([[   3.89520355,   18.16041919,    9.94437727,   32.        ],
        [  23.12777106,  107.82748892,   59.04474002,  190.        ],
        [  21.66706973,  101.01733172,   55.31559855,  178.        ],
        [  29.82265216,  139.04070939,   76.13663845,  245.        ],
        [ 191.35187424,  892.1305925 ,  488.51753325, 1572.        ],
        [   2.92140266,   13.62031439,    7.45828295,   24.        ],
        [   3.89520355,   18.16041919,    9.94437727,   32.        ],
        [   4.26037888,   19.86295848,   10.87666264,   35.        ],
        [   4.01692866,   18.72793229,   10.25513906,   33.        ],
        [   5.72108021,   26.67311568,   14.60580411,   47.        ],
        [   7.06005643,   32.91575977,   18.0241838 ,   58.        ],
        [   4.26037888,   19.86295848,   10.87666264,   35.        ],
        [ 302.        , 1408.        ,  771.        , 2481.        ]]))

In [76]:
marital = pd.crosstab(survey.marital,survey.happy, margins =True)

In [77]:
stats.chi2_contingency(observed = marital)

(260.68943894182826,
 7.762777322980048e-47,
 15,
 array([[  53.6969697 ,  248.58538324,  140.71764706,  443.        ],
        [ 162.06060606,  750.24527629,  424.69411765, 1337.        ],
        [  79.27272727,  366.98609626,  207.74117647,  654.        ],
        [  11.15151515,   51.62495544,   29.22352941,   92.        ],
        [  33.81818182,  156.55828877,   88.62352941,  279.        ],
        [ 340.        , 1574.        ,  891.        , 2805.        ]]))

Conclusion: c. Since P-value < Significance value(5%) so reject the Null. Stats value of marital is greater than earnings.
Therefore, Happiness is more driven by Marital Status than Earnings.